# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  VERSION: "1.0-canary"

services:
  - docker:dind

stages:
  - build
  - dockerize

before_script:
  - docker info

buildTriplifier:
  stage: build
  image: maven:3.5.3-jdk-8
  artifacts:
    paths:
      - javaTool/target/*.jar
  tags:
    - um-cds
  script:
    - cd javaTool && mvn clean package

dockerize:
  stage: dockerize
  tags:
    - um-cds
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$VERSION" .
    - docker push "$CI_REGISTRY_IMAGE:$VERSION"
