name: Java build & containerize

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
      - 'release/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd javaTool
          mvn --batch-mode --update-snapshots package
      - name: Move to artifact folder
        run: |
          mkdir artifacts
          cp javaTool/target/*.jar artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: triplifier_jar
          path: artifacts
  containerize:
    runs-on: ubuntu-latest
    needs: build-java

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: triplifier_jar
          path: .
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch != 'main'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ steps.extract_branch.outputs.branch }}
      - name: Build container
        id: docker_build_main
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch == 'main'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ steps.extract_branch.outputs.branch }}, ghcr.io/${{ env.REPO }}:latest