name: Java build & containerize

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd javaTool
          mvn --batch-mode --update-snapshots package
      - name: Move to artifact folder
        run: |
          mkdir artifacts
          cp javaTool/target/*.jar artifacts
      uses: actions/upload-artifact@v3
        with:
          name: Package
          path: artifacts