name: Build and Publish

on:
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        run: |
          python -m pip install --upgrade twine
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Bump version in pyproject.toml
        id: bump_version
        run: |
          pip install toml
          python .github/scripts/bump_version_number.py      
      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}"
          git push

      - name: Create branch for new version if on main
        if: github.ref == 'refs/heads/main'
        run: |
          version=${{ steps.bump_version.outputs.new_version }}
          git checkout -b version/${version}
          git push origin version/${version}
