name: Build and Publish

on:
  push:
    branches:
      - main
      - release/*

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to GitHub Packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.GITHUB_TOKEN }}
          repository-url: https://pypi.pkg.github.com/${{ github.repository_owner }}
